// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.iOS.Views;
using UIKit;

namespace SampleApp
{
    [MvxFromStoryboard(StoryboardName = "Main")]

    public partial class MainViewController : MvxViewController<SignInViewModel>
    {
        bool isinitialized = false;
        public MainViewController(IntPtr handle) : base(handle)

        {
            isinitialized = true;
            // ViewDidLoad();
        }


        public override void ViewDidLoad()
        {
            if (!isinitialized)
                return;
            base.ViewDidLoad();
            if (ViewModel == null)
            {
                ViewModel = new SignInViewModel();

            }
            var source = new SignInTableSource(ViewModel, loginTableView);
            loginTableView.Source = source;
            var set = this.CreateBindingSet<MainViewController, SignInViewModel>();
            set.Bind(source).To(vm => vm.LoggedInUser);


            set.Apply();


            loginTableView.ReloadData();
        }
    }
}
